### ISSUE TITLE
Set/add XP greater than 1 million

### ISSUE THREAD

**Issue by AxelTerizaki** [almeidx/lurkr-website#337]
**Is your feature request related to a problem? Please describe.**

I had a bot I made myself (which took MEE6's XP at some point) and I wanted to switch away from it to Lurkr because I don't have time to maintain it anymore. Since I can't import my current stats (it's just a CSV with XP and user IDs) I wanted to set people's Xp manually but I realize the slash command won't let me add anything above 1 million. (I have a user with 2,3 million XP for example. The server has been existing since 2015) 

**Describe the ideal solution**

Do not put a upper limit to how many XP can be set with the /xp commands

**Describe alternatives you've considered**

It's a lot to ask but a way for people to import their data manually through a CSV in addition of from other bots would be nice.

**Comment by almeidx** [comment]
This will be included in the next bot update. 
You can be notified about it here: https://discord.com/channels/705009450855039039/951585846367248424
