### ISSUE TITLE
Allow add/set message count commands

### ISSUE THREAD

**Issue by AxelTerizaki** [almeidx/lurkr-website#520]
**Is your feature request related to a problem? Please describe.**

I wanted to import stats from a bot I made. I managed to set everyone's XP thanks to your commands, but I'd like to modify their message numbers as well on the leaderboards, and right now that's not possible :)

**Describe the ideal solution**

Have /messages set/add etc. commands to the bot.

Thanks in advance! :)

**Comment by almeidx** [comment]
The sum of messages will be used as a public statistic so we will likely not add this.
