### ISSUE TITLE
Cookies Popup Crashes Dashboard

### ISSUE THREAD

**Issue by realCmdData** [almeidx/lurkr-website#615]
**Describe the bug**
When clicking on "Accept" on the cookies popup the dashboard crashes and presents a 404 screen

**To Reproduce**
If applicable, steps to reproduce the behavior:

1. Log out if already logged in
2. Log back in to get the cookies pop up
3. Do not click accept and navigate straight to the dashboard, and select a server
4. In the dashboard overview, click accept.

**Expected behavior**
Cookies popup should go away

**Screenshots**

https://github.com/user-attachments/assets/7f21a3fa-8db2-482e-8e0f-48d487fce25d

**Comment by almeidx** [comment]
Should be fixed by 7edf287ca18215b96b9619a0e5a498a187347222
