### ISSUE TITLE
Adding roles to an existing multiplier doesn't save correctly

### ISSUE THREAD

**Issue by realCmdData** [almeidx/lurkr-website#616]
**Describe the bug**
Adding roles to an existing multiplier doesn't save correctly

**To Reproduce**
1. Add a multiplier to the dashboard with at least one role, and save.
2. Reload the page and observe that the multiplier and role stay the same.
3. Add a role to the existing multiplier, and save.
4. Reload the page and observe that the additional role is remove and isn't added to the database

**Expected behavior**
The saving action should add the additional role to the existing multiplier

**Screenshots**

https://github.com/user-attachments/assets/f3c17d1e-3480-4bd5-8912-115459ec724f

**Comment by almeidx** [comment]
Fixed in https://github.com/almeidx/lurkr/commit/1bcfea0163429338470f5761978686fe2d0d142f
